@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjFiM2UzYjIyMWUxYmY3NTZiM2NhMzUiLCJpYXQiOjE3MTU3MzI3MDl9.7HmGLINNdJBCCBx9-FKvdCAR1WbBAc5JgxRqOXtU4ds

###

POST http://localhost:8000/users
content-type: application/json

{
    "name": "teste",
    "email": "teste@teste.com",
    "password": "123"
}

###

POST http://localhost:8000/auth/login
content-type: application/json

{
    "email": "teste@teste.com",
    "password": "13"
}

###

GET http://localhost:3000/users
Authorization: Bearer {{token}}

###

GET http://localhost:3000/projects
Authorization: Bearer {{token}}

###

POST http://localhost:3000/projects
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "projeto1",
    "participants": [
        "661b3e3b221e1bf756b3ca35"
    ]
}

###

PUT http://localhost:8000/projects/66205a2826ca311a1d1b1889
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "projeto4"
}

###

PUT http://localhost:3000/folders/6643ffe989cd19065068c4c3
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "front-end",
    "folderId": "6643ffe989cd19065068c4c3"
}

###

POST http://localhost:8000/folders
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "front-end",
    "projectId": "66179f9bead69ec71fc8895f"
}

###

POST http://localhost:8000/columns
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "Em andamento",
    "folderId": "6617a61b372c1c22c5527e26"
}

###

PUT http://localhost:8000/columns/6617aba7cb6cf1edd97a9163
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "Em andamento2"
}

###

DELETE http://localhost:8000/columns/6617aba7cb6cf1edd97a9163
Authorization: Bearer {{token}}

###

POST http://localhost:8000/tasks
content-type: application/json
Authorization: Bearer {{token}}

{
    "title": "Bug cadastro",
    "description": "Corrigir bug na tela de cadastro",
    "columnId": "6617b0e2cb6cf1edd97a916b"
}

###

PUT http://localhost:8000/tasks/6617b68a5dbe07b769084ba4
content-type: application/json
Authorization: Bearer {{token}}

{
    "title": "Bug cadastro 2"
}

###

DELETE http://localhost:8000/tasks/6617b68a5dbe07b769084ba4
Authorization: Bearer {{token}}